### ISSUE TITLE
dictionary function support for :Breakadd

### ISSUE THREAD

**Issue by kota65535** [tpope/vim-scriptease#22]
Do you have a plan for supporting dictionary functions for :Breakadd?
Script using dictionary functions is often long and difficult to understand, so adding this feature will be incredibly helpful for us.

**Comment by tpope** [comment]
Anonymous dictionary functions -- `function dict.func()` -- are impossible to track, as far as I know. I recommend creating regular functions `function s:func() dict` instead and assigning them to a dictionary `let dict.func = function('s:func')` instead.

**Comment by kota65535** [comment]
Thanks for your advice, I will rewrite them to do so.
