### ISSUE TITLE
:Vfind – an extended :Vedit

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-scriptease#26]
I think it would be even more convenient to have a command (something in the spirit of `:Vfind` or `$ which -a vim`) which searches all vim recognized subfolders:

	This is a list of directories which will be searched for runtime
	files:
	  filetype.vim	filetypes by file name |new-filetype|
	  scripts.vim	filetypes by file contents |new-filetype-scripts|
	  autoload/	automatically loaded scripts |autoload-functions|
	  colors/	color scheme files |:colorscheme|
	  compiler/	compiler files |:compiler|
	  doc/		documentation |write-local-help|
	  ftplugin/	filetype plugins |write-filetype-plugin|
	  indent/	indent scripts |indent-expression|
	  keymap/	key mapping files |mbyte-keymap|
	  lang/		menu translations |:menutrans|
	  menu.vim	GUI menus |menu.vim|
	  plugin/	plugin scripts |write-plugin|
	  print/	files for printing |postscript-print-encoding|
	  spell/	spell checking files |spell|
	  syntax/	syntax files |mysyntaxfile|
	  tutor/	files for vimtutor |tutor|

Occasionally, it is not clear whether the file you have in mind is in `ftplugin`, `plugin`, `autoload` or you know that there is only a `scriptease.vim` in the folder `plugin` so you do not have to prepend the expected foldername. Instead of typing `:Ve plugin/scriptease.vim` you can enter `:Vf scriptease.vim`.

**Comment by tpope** [comment]
It's extremely common to have the same filename in multiple folders, so I'm skeptical of how useful this would be.

**Comment by kiryph** [comment]
Of course, you are right that the same filename often appears in multiple folders.
However, this already applies to `:Vedit` which returns several files as well if there is one in 

1. `$HOME/.vim`,
2. 						`$VIM/vimfiles`,
3. 						`$VIMRUNTIME`,
4.						`$VIM/vimfiles/after`,
5.						`$HOME/.vim/after`,
5. and possibly even more when using pathogen or any other `rtp` manager (vim-plug, vundle, etc.) which extends `rtp`.

Actually, I also had this situation in mind where the same filename occurs in multiple folders:
the user wants to figure out which files are possibly related to what she/he is looking for and wants to get a list of all files.

`:Vfind` can return a single file, short or long list of files (as `:Vedit` does).

Currently, I see use for this in following circumstances (possibly others have further use cases):

1. list of all files anywhere on rtp which vim recognizes
2. user has forgotten where the file is (global/local, after/non-after, plugin/autoload)
3. shorten the command to open unique files as described above.

For instance `vinegar.vim` also has a setting for netrw syntax which I didn't know until I had searched for this. What I mean is, not all syntax related stuff must be located in `syntax/<netrw>.vim` but can be somewhere else. And non-syntax related stuff can be in `syntax/<netrw>.vim`. There is no clear separation enforced by vim anyhow.

When I think about this, a `:Vgrep` could also be useful.

**Comment by tpope** [comment]
The difference is that when a file appears in for example both `$HOME/.vim` and `$VIMRUNTIME`, the former takes precedence. The main exception is for `after/` files, but those you can reach explicitly by prepending `after/`.

You can do `:Vedit */ruby.vim` to get all files named like that, if you really want to. I really don't think it justifies a separate command.

I have experimented with creating a `:Vgrep` in the past, but it gets weird the way some runtime directories are nested inside of others. Please do investigate that further.

**Comment by kiryph** [comment]
I can see that `:Vfind` is close to `:Vedit`. Actually, I would say it is the other way around. However, I still think a file search on rtp is not completely useless.
Since globbing with wildcards works here very well because all files are almost surely in exactly one subfolder, `*/filename` can mimick the proposed behaviour of Vfind. Therefore I can understand your objection against a new command.
Thanks for reminding me of this.

Regarding vgrep: could you show me your experiment and be more specific why it gets weird the way some runtime directories  are nested?
However, this does not have a high priority for me and your knowledge is far better than mine which makes me hesitate to investigate this.
I close this issue since Vfind is off the table. When I find the time to investigate Vgrep I will open a separate issue.

**Comment by tpope** [comment]
I don't think I have a copy of my experiment any more. The problem is that if the runtime path contains both `.vim` and `.vim/bundle/vim-scriptease`, you'll get duplicate results.

**Comment by kiryph** [comment]
So rtp should have to be reduced to common longest paths, see e.g. http://superuser.com/a/1042593/161119.

**Comment by tpope** [comment]
Yes something like that.
