### ISSUE TITLE
No manual entry for...

### ISSUE THREAD

**Issue by light2yellow** [tpope/vim-scriptease#27]
Unfortunately, when navigating to any link to another vim manual entry and uppercase K doesn't work. But a usual `:h %entry%` works. What am I doing wrong?

**Comment by tpope** [comment]
Once your within the help, further navigation is best achieved with tags: `CTRL-]`. I made a judgment call not to provide `K` as an alternative.

**Comment by light2yellow** [comment]
Right now I figured out that K is not working in .vimrc either (no entry).
