### ISSUE TITLE
Feature Request - add filetype to Verbose preview window

### ISSUE THREAD

**Issue by fourjay** [tpope/vim-scriptease#33]
I'd like to add some behavior to the Verbose preview window. Please consider adding a (scriptease specific filetype to the preview window ``scriptease#verbose_command()`` to give a hook to trigger modifications off of.
Among other things, I'd add a ``<nowait>`` to the q mapping, but I'd consider some personal navigation commands etc.
I'd expect it could be as simple as adding another command, ``set ft=scripteaseverbose``, into the exe chain.

**Comment by tpope** [comment]
`scripteaseverbose` is a mouthful but yeah I think that would be reasonable.
