### ISSUE TITLE
iskeyword: colon

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-scriptease#39]
I've found that vim-scriptease removes the colon from `iskeyword`:

https://github.com/tpope/vim-scriptease/blob/6ae8cb72abfca0a7b4bd1243f721681f58aabf13/plugin/scriptease.vim#L115-L117

It mentions that this would break tags, but for me removing `:` breaks tags, since a colon is included with script-local functions (`s:foo`).

You are not using https://github.com/universal-ctags/ctags then, are you?

**Comment by tpope** [comment]
I don't use universal-ctags. I wish they would cut a release so I could.

I'm pushing up a configuration flag to opt out because I certainly don't want this to block anything. Maybe at some point I'll replace it with a bunch of tag maps like in vim-ruby.

**Comment by tpope** [comment]
Let me just add that `iskeyword+=:` also makes `*` behave weird. And it has terrible implications for `<SID>function`.

**Comment by blueyed** [comment]
Yeah, I know that having `iskeyword` bound to tag selection is not ideal..

I wish there was something like "try with isk+=:" if no tag was found (or a separate setting like tags_iskeyword, but then new settings are not ideal either).
I guess this could be done rather easily in a custom function probably, but would have to wrap various mappings for tag navigation then (although `g<C-]>` would be fine for me in the beginning).

> I wish they would cut a release so I could.

Might take a while: https://github.com/universal-ctags/ctags/issues/1038
But it is not hard to build yourself, and has many nice additions.

**Comment by tpope** [comment]
Yeah, that's what vim-ruby does, has a custom `cmap` to get the tag under the under the cursor and then 9 different jump to tag maps that invoke it. Scriptease could use the same approach and generate a tag like `/^\%(s:\)\=function$`.

Rather than maintain a duplicate implementation of those 9 maps, I could see just providing the `cmap` and punting to another plugin for the tag maps.

**Comment by blueyed** [comment]
I see.
That would be useful.
But more useful would be an actual patch for Vim I'd say.
What do you think could Vim provide to help with this itself already?

**Comment by tpope** [comment]
> Is this moot?

Presuming the answer is yes.
