### ISSUE TITLE
Feature request/idea: a helper command for redirecting to a buffer

### ISSUE THREAD

**Issue by deathlyfrantic** [tpope/vim-scriptease#40]
I found myself wanting to look through all my autocmds and the only way I could think to do it was redirecting the output of `autocmds` to a register and pasting that into a new buffer. Any chance you'd consider adding a command to handle that more easily for arbitrary commands? Something like `:Redir autocmds`. I think it matches the intent of e.g. `:Messages`.

**Comment by tpope** [comment]
`:Verbose` does this. Use `:0Verbose` if you don't want a higher verbose level.
