### ISSUE TITLE
`:{count}Verbose` doesn't work in an empty buffer

### ISSUE THREAD

**Issue by lacygoill** [tpope/vim-scriptease#43]
Hello,

Some commands in vim-scriptease are defined with the `-range=N` attribute, and can be prefixed with a count. This is the case, as an example, for the `:Verbose` command, to temporarily increase Vim's verbosity level.

Since Vim's patch [8.1.1241](https://github.com/vim/vim/commit/b731689e85b4153af7edc8f0a6b9f99d36d8b011), the command doesn't always work anymore. That is, if you prefix `:Verbose` with a count greater than 1, in an empty buffer, Vim complains with the error `E16: Invalid range`.

I think that's because the range is interpreted as the line of an address, and there's no line whose address is greater than 1 in an empty buffer.

Here's a MWE:

    com! -range=1 Cmd echo 'test'

Run `:3Cmd` in an empty buffer, and `E16` will be raised.

I think the solution is to specify that the type of the range is `other` (which doesn't exist yet in Nvim):

    com! -range=1 -addr=other Cmd echo 'test'
                  ^^^^^^^^^^^

At least, it does fix the issue on my machine.

Do you think that Vim's patch 8.1.1241 introduced a regression, or is it working as intended, and you're now expected to use `-addr=other` whenever you want to use `-range` for some arbitrary count, not tied to any specific type (line address, buffer number, window number, ...)?

**Comment by tpope** [comment]
Bram is extremely dedicated to backwards compatibility so I'd say this is a regression. I think adding `-addr=other` is still a good idea if it's available. Looks like `has('patch-8.1.560')` would be the correct conditional.
