### ISSUE TITLE
Feature Request : Vgrep

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-scriptease#46]
Sometimes I just want to grep through the vim plugins, I can easily write something on my own but feel like this plugin might be a good place for this.

If you think there's value, I can work on a PR.

**Comment by tpope** [comment]
This is way harder than it sounds because of nesting: `~/.vim/pack/start/foo/after/plugin/bar.vim` will get searched 3 times if you do it the naive way. But please do investigate.

**Comment by dhruvasagar** [comment]
Do you think running grep against all directories in `'packpath'` should suffice ? Should be much easier to implement

**Comment by tpope** [comment]
That doesn't solve the `after/` problem.

**Comment by dhruvasagar** [comment]
@tpope I think I don't exactly understand the problem, why would the after path as you said above get searched 3 times ?

**Comment by tpope** [comment]
`grep a a/b` searches `a/b` twice.

**Comment by dhruvasagar** [comment]
@tpope That shouldn't be a problem when dealing with packpath, since no two paths are going to have any overlap
