### ISSUE TITLE
Could not determine script id when setting breakpoint inside s: function

### ISSUE THREAD

**Issue by petobens** [tpope/vim-scriptease#49]
Consider the following simple `foo.vim` file:
```viml
function! s:Foo()
    let x = 2
    return x + 1
endfunction

echo s:Foo()
```
Now if I open nvim and do `Breakadd here` inside the `s:Foo` function I get and error saying
```
Could not determine script id
```
If I now run `:Runtime` on that file and repeat the process of setting the breakpoint inside the function then the breakpoint is correctly set. So my question is: is it possible to set a breakpoint within an s: function without having to run `:Runtime` first? I guess the answer is no but any pointer/explanation is appreciated. Thanks in advance.

**Comment by tpope** [comment]
The script id is an autoincrementing integer. It's assigned when you source the file. Expecting Vim to preemptively hand out script ids to every file in the file system is ... unrealistic.
