### ISSUE TITLE
Jump to :verb output files

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-scriptease#50]
I often `:verb map` or `:verb set` to find out which file is responsible for configuration – but need to manually go the file itself. `:Verbose map` is better – at least I can jump to the file – but still have to handle the line number manually.

It would be great if `:Verb map` and `:Verb set` loaded results in the quickfix list.

**Comment by idbrii** [comment]
If you use verbose to look at a mapping and you use `gF` (capital F) on one of those files, vim will jump you to the file **and line**. Support for this specific format requires a somewhat recent version of vim: https://github.com/vim/vim/commit/64e74c9cc7d5aab215cf72d9bdd3aac32e128191

```vim
:Verbose map g=
:call search('vim')
:normal gF
```

Would open a buffer with:
```
:Verbose map g=
x  g=            <Plug>ScripteaseFilter
	Last set from ~/vim/bundle/scriptease/plugin/scriptease.vim line 98
n  g==           <Plug>ScripteaseFilter<SNR>151__
	Last set from ~/vim/bundle/scriptease/plugin/scriptease.vim line 95
n  g=            <Plug>ScripteaseFilter
	Last set from ~/vim/bundle/scriptease/plugin/scriptease.vim line 94
```

and jump to scriptease.vim line 98.

**Comment by odnoletkov** [comment]
TIL <kbd>gF</kbd> works with many formats other than just `path/to/file:12`. Thanks, @idbrii!
