### ISSUE TITLE
Scriptnames doesn't work with cfdo

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-scriptease#54]
For example, try running `:Scriptnames` followed by `:cfdo echo %` - nothing happens. I'd expect the filenames to be echoed.

**Comment by tpope** [comment]
Looks like `:cfdo` only works for quickfix entries with line numbers. I don't think I want to add a `|1|` to every line just so `:cfdo` will work?

**Comment by rgrinberg** [comment]
That's a shame because doing something like `:cfdo lvimgrepadd /foo/g %` is pretty useful.

**Comment by tpope** [comment]
Isn't that slow as heck?

**Comment by rgrinberg** [comment]
To workaround this issue, I load scriptnames into args with a hack and vimgrep that. With just under 100 plugins, it takes no more than a couple of seconds to search everything this way.

**Comment by tpope** [comment]
You could probably use `scriptease#scriptnames_qflist()` to do it in a less hacky way.
