### ISSUE TITLE
E149: Sorry, no help for :Plug

### ISSUE THREAD

**Issue by acamso** [tpope/vim-scriptease#57]
Hi, I was playing around with the `<K>` mapping and there may be a bug for `Plug` in these contexts:

```
Plug 'tpope/vim-scriptease'  # 1st column
  Plug 'tpope/vim-scriptease'  # with tab
```
Not sure if it's my setup, but maybe someone can verify. I guess it has to do with `scriptease#helptopic()` and an uppercase char as the 1st char of the line.

**Comment by tpope** [comment]
`:Plug` is the correct help topic. Maybe you don't have help tags for vim-plug generated?
