### ISSUE TITLE
Is a :SyntimeReport command possible?

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-scriptease#58]
in the spirit of `:Messages`, `:Scriptnames`.

Right now I do following to the see full report which is usually longer than the screen.
```viml
:syntime on
" scroll in file with slow syntax file (e.g. tex with vimtex and fontawesome5 latex syntax)
:redir > syntimereport.txt
:syntime report
:e syntimereport.txt
```

I am not sure if it is possible to get the actual lines of the syntax groups in the syntax file. Vim help mentions that the name is not necessarily unique:
```
			NAME		Name of the syntax item.  Note that
					this is not unique.
```

Maybe loading the report into the preview window for full view and easy navigation would be a first step.

**Comment by tpope** [comment]
`:Verbose syntime report` will do largely the same thing. `:Messages` and `:Scriptnames` both do additional parsing. I don't think that's necessary here.
