### ISSUE TITLE
How can you debug a local "s:" function while NOT inside its Vimscript file?

### ISSUE THREAD

**Issue by mbwgh** [tpope/vim-scriptease#59]
Sorry if this is just uninformed, but I am having a really hard time wrapping my head around what the workflow is supposed to be with this.

In trying to debug a vim plugin which is active for a certain filetype (vimwiki, `.wiki` files).

Upon certain keyboard actions (pressing o or Enter on a specific line in the `.wiki` file), some vimwiki-specific functions are invoked which cause a noticeable slowdown.

I was able to get the following to work so far, using Vim's standard debug functionality:
```VimScript
:123  "go to specific line
:debug normal o  "Insert a new line. This command is very slow.
:breakadd func vimwiki#lst#kbd_o
```

This makes the debugger break on `kbd_o` and I can step and echo variables.

But all the action happens in some other local "s:" functions, for which `:breakadd` apparently does not work.
This is what `:Breakadd` (according to the documentation) supports, but it is only available when inside a vimscript file.

Since these "s:" functions are not pure functions, but work on some non-trivial buffer contents, I (believe I) can't just call them with their arguments while inside the Vimscript file where they are defined.

Is it possible to add a breakpoint for this local function and still start debugging like described above?

**Comment by tpope** [comment]
Switch to the file with the function, `:Breakadd` it, and switch back?
